## numpy

In [1]:
import numpy as np


In [22]:
L=list(range(1,6))
c=L
np_L=np.array(L)
np_c=np.array(c)

In [18]:
print("orig L=",L)
print("orig c=L",c)


orig L= [1, 2, 3, 4, 5]
orig c=L [1, 2, 3, 4, 5]


In [19]:
## 改了 c[2]=-1
c[2]=-1
print("updated c=",c)
print("L=",L)

updated c= [1, 2, -1, 4, 5]
L= [1, 2, -1, 4, 5]


In [23]:
print("np.array(L)=", np_L)
print("np.array(c)=", np_c)

np.array(L)= [1 2 3 4 5]
np.array(c)= [1 2 3 4 5]


In [24]:
np_c[2]=-1
print("np.array(L)=", np_L)
print("np.array(c)=", np_c)

np.array(L)= [1 2 3 4 5]
np.array(c)= [ 1  2 -1  4  5]


In [25]:
type(np_L)

numpy.ndarray

In [38]:
arr=np.array(range(1,13))
print(arr)
print(arr.shape)
newarr=arr.reshape(4,3)
print(newarr, newarr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [42]:
import numpy as np
a = np.array([1.1, 2.2, 3.3, 0, -1])
b = np.array(a, dtype='?')
c = np.array(a, dtype='U')
d = np.array(a, dtype='S')
e = np.array(a, dtype='B')
f = np.array(a, dtype='i')
print(a, "資料型態=", a.dtype)   # [ 1.1  2.2  3.3  0.  -1. ]
print(b, "資料型態=", b.dtype)   # [ True  True  True False  True]
print(c, "資料型態=", c.dtype)   # ['1.1' '2.2' '3.3' '0.0' '-1.0']
print(d, "資料型態=", d.dtype)   # [b'1.1' b'2.2' b'3.3' b'0.0' b'-1.0']
print(e, "資料型態=", e.dtype)   # [  1   2   3   0 255]
print(f, "資料型態=", f.dtype)   # [ 1  2  3  0 -1]

[ 1.1  2.2  3.3  0.  -1. ] 資料型態= float64
[ True  True  True False  True] 資料型態= bool
['1.1' '2.2' '3.3' '0.0' '-1.0'] 資料型態= <U32
[b'1.1' b'2.2' b'3.3' b'0.0' b'-1.0'] 資料型態= |S32
[  1   2   3   0 255] 資料型態= uint8
[ 1  2  3  0 -1] 資料型態= int32


In [46]:
## astype 轉型態
a=np.array([1,2,4,8], dtype="int32")
b=a.astype("float32")
print(a, "資料型態=",a.dtype)
print("b=a.astype('float32')")
print(b, "資料型態=",b.dtype)

[1 2 4 8] 資料型態= int32
b=a.astype('float32')
[1. 2. 4. 8.] 資料型態= float32


In [58]:
L_2D=[[1,2,4],
      [4,8,16]]
arr_2D=np.array(L_2D)

print(arr_2D, "shape=", arr_2D.shape)
arr_2D=arr_2D.reshape(3,2)
print(arr_2D, "shape=", arr_2D.shape)

[[ 1  2  4]
 [ 4  8 16]] shape= (2, 3)
[[ 1  2]
 [ 4  4]
 [ 8 16]] shape= (3, 2)


In [63]:
## 概念如同 python內建 range()產生固定間距的陣列,
a=np.arange(10)
print(a)

b=np.arange(1,10,0.1)
print(b)

c=np.arange(1,10,dtype='float')
print(c)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [66]:
lspc=np.linspace(5,10,10)
print(lspc)

interval=(10-5)/9
print(interval)
tmp=5
for i in range(10):
    tmp+=interval
    print(tmp)

[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]
0.5555555555555556
5.555555555555555
6.111111111111111
6.666666666666666
7.222222222222221
7.777777777777777
8.333333333333332
8.888888888888888
9.444444444444443
9.999999999999998
10.555555555555554


In [67]:
arr_3d=np.arange(24).reshape(2,3,4)
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [90]:
## 典型 list的3維, 來體會一下怎麼取值

L=[ [[1,2,3],
     [4,5,6]] ,
    [[7,8,9],
     [10,11,12]]
  ]

print(L[0]) ## 第一個維度index=0 取出一個 2D (2x3 array)
print(L[1]) ## 第一個維度index=1 取出一個 2D (2x3 array)

print("====")
print(L[0][1]) ## 取出的 2D array, 取 index=1的 1D array (向量,list)
print(L[1][1])

[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]
====
[4, 5, 6]
[10, 11, 12]


In [91]:
## 用 numpy 的 array來操作的話: 
a=np.array([[1,2,3,4,5], [6,7,8,9,10], [15,14,13,12,11]])
print(a[1])

## 利用 [x:y]來slice 切割array, 好用!
print(a[1, 0:3])
print(a[:, 1:3])

[ 6  7  8  9 10]
[6 7 8]
[[ 2  3]
 [ 7  8]
 [14 13]]


## 布林值取值! 也很重要的篩選技巧



In [92]:
b=np.array(range(1,16))
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [93]:
print(b[b>5])

[ 6  7  8  9 10 11 12 13 14 15]


In [102]:
tmp=[[e+i for e in range(3) ] for i in range(4)]
print(tmp)
c=np.array(tmp)
print(c)

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [123]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b[...,::2])

[[[ 1  3]
  [ 4  6]]

 [[ 7  9]
  [10 12]]]


In [126]:
for i in np.nditer(b[:, 0:1]):
    print(i)

1
2
3
7
8
9


## assign value

In [131]:
import numpy as np
a = np.zeros((5,5))
a[0][0] = 1
a[1][1] = 2
a[2][2] = 3
a[3][3] = 4
a[4][4] = 5
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [132]:
a[0,[2,3]]=100
print(a)

[[  1.   0. 100. 100.   0.]
 [  0.   2.   0.   0.   0.]
 [  0.   0.   3.   0.   0.]
 [  0.   0.   0.   4.   0.]
 [  0.   0.   0.   0.   5.]]


## 修改 array形狀
reshape(),
flaten(),
transpose(), .T

In [146]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a, ", shape=",a.shape)

a=a.reshape((2,4))
print(a)


[[1 2]
 [3 4]
 [5 6]
 [7 8]] , shape= (4, 2)
[[1 2 3 4]
 [5 6 7 8]]


### flatten()能將多維度的陣列，扁平化成一維陣列，可以設定 order 參數調整扁平的順序，預設為 C，表示先水平再垂直，設定為 F 表示先垂直再水平。

In [155]:
print("a=",a)
c=a.flatten('C') ##C，表示先水平再垂直
print("a.flatten=",c,"by C")
d=a.flatten('F') ##F 表示先垂直再水平
print("a.flatten=",d, "by F")

a= [[1 2 3 4]
 [5 6 7 8]]
a.flatten= [1 2 3 4 5 6 7 8] by C
a.flatten= [1 5 2 6 3 7 4 8] by F


## 軸向觀念
axis 0 <br/>
axis 1 <br/>
axis 2 <br/>
[1,3,5] => (3,) => axis0 => [1,3,5]

[[2,4,6], [8,10,12]] => (2,3) => axis0 => [2,8],[4,10],[6,12]

### 修改陣列項目


In [160]:
a=np.array([[1,2,4],[2,5,3]])
b=np.resize(a, (3,2))
c=a.reshape((2,3))
print(a)
print(b)
print(c)

[[1 2 4]
 [2 5 3]]
[[1 2]
 [4 2]
 [5 3]]
[[1 2 4]
 [2 5 3]]


In [163]:
## np.resize 可以維度變大... 但是填充的數字... 
e=np.resize(a, (3,4))
print(e)

[[1 2 4 2]
 [5 3 1 2]
 [4 2 5 3]]


In [164]:
## 用 np.append添加元素:
a = np.array([[1,1,1],[2,2,2]])
b = np.append(a, 1)
c = np.append(a, [3,3,3])
print(b)   # [1 1 1 2 2 2 1]
print(c)   # [1 1 1 2 2 2 3 3 3]

[1 1 1 2 2 2 1]
[1 1 1 2 2 2 3 3 3]


In [168]:
a = np.array([[1,1,1],[2,2,2]])
b = np.append(a, [[3,3,3],[4,4,4]],1)
print("沿著 axis1 append=")
print(b)
# ''' 這邊用一個逗號 , 顯示區隔 append的作用:
# [[1 1 1,3 3 3]
#  [2 2 2,4 4 4]]
# '''
c = np.append(a, [[3,3,3],[4,4,4]],0)
print("沿著 axis0 append=")
print(c)
# '''
# [[1 1 1]
#  [2 2 2]
#  [3 3 3]
#  [4 4 4]]
# '''

沿著 axis1 append=
[[1 1 1 3 3 3]
 [2 2 2 4 4 4]]
沿著 axis0 append=
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [170]:
## padding填充
a=np.array([-2,-1,0,1,2])
b=np.pad(a,5)
print(b)

c=np.pad(a,(2,3)) ## 左邊填充2個右邊3個
print(c)

[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[ 0  0 -2 -1  0  1  2  0  0  0]


In [172]:
## 切割
a=np.array([1,2,3,4,5,6])
b=np.array_split(a,3)
c=np.split(a,3)
print(a)
print(b)
print(c)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [187]:
## 連接 concatenate
a = np.array([[1,1],[2,2],[3,3]])      # 3x2 陣列
b = np.array([[4,4],[5,5],[6,6]])      # 3x2 陣列
# b = np.array([[4,4],[5,5],[6,6,6]])  # 如果 b 的形狀和 a 不同，會發生錯誤
c = np.concatenate((a, b), axis=0)     # axis 設定為 0
print(c)                               # 連接變成 6x2 陣列
# '''
# [[1 1]
#  [2 2]
#  [3 3]
#  [4 4]
#  [5 5]
#  [6 6]]
# '''

d = np.concatenate((a, b), axis=1)     # axis 設定為 1
print(d)                               # 連接變成 3x4 陣列
# '''
# [[1 1 4 4]
#  [2 2 5 5]
#  [3 3 6 6]]
# '''

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]
[[1 1 4 4]
 [2 2 5 5]
 [3 3 6 6]]


In [193]:
a=a.reshape(2,3)
print(a)
print(b)
c=np.concatenate((a,b.reshape(2,3)),axis=1)
print(c)


[[1 1 2]
 [2 3 3]]
[[4 4]
 [5 5]
 [6 6]]
[[1 1 2 4 4 5]
 [2 3 3 5 6 6]]


In [194]:
test1=np.arange(10,30,2)
print(test1)

[10 12 14 16 18 20 22 24 26 28]


In [204]:
test2=np.arange(12)
print("orig=",test2)
print()
a=test2.reshape(4,3)
print("dim:4x3=\n",a)
print()
b=np.resize(test2,(2,3,5))
print("dim:2x3x5=\n",b)

orig= [ 0  1  2  3  4  5  6  7  8  9 10 11]

dim:4x3=
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

dim:2x3x5=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11  0  1  2]]

 [[ 3  4  5  6  7]
  [ 8  9 10 11  0]
  [ 1  2  3  4  5]]]


In [210]:
test3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
test3.flatten('F')

print(a.flatten('C'))
print(a.flatten('F'))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  3  6  9  1  4  7 10  2  5  8 11]


### 排序


In [213]:
arr=np.array([[2,3,1],
              [5,2,0],
              [3,1,5]])
b=np.sort(arr) ## 預設 axis=1去排序
c=np.sort(arr,axis=1)
print(b)
print(c)

[[1 2 3]
 [0 2 5]
 [1 3 5]]
[[1 2 3]
 [0 2 5]
 [1 3 5]]


In [214]:
d=np.sort(arr,axis=0) ## axis=0, 垂直的元素by元素排序
print(d)

[[2 1 0]
 [3 2 1]
 [5 3 5]]


In [219]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("max index=",np.argmax(arr))
print("min index=",np.argmin(arr))

max index= 8
min index= 0


## 廣播


In [222]:
## 基本上就 numpy+-*/運算的背後實作
a=np.array([[1,2,3],[4,5,6]])

print(a+2)
print(a-2)
print(a*2)
print(a/2)

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [223]:
#若是另一個 array要來跟 a做 廣播運算, 同一個維度上數量要相等或等於1才能做
b=np.array([7,8,9])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 8 10 12]
 [11 13 15]]
[[-6 -6 -6]
 [-3 -3 -3]]
[[ 7 16 27]
 [28 40 54]]
[[0.14285714 0.25       0.33333333]
 [0.57142857 0.625      0.66666667]]


## 搜尋

In [228]:
# np.where
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b=np.where(a>3)
print(b) 
## >> (array([1, 1, 1]), array([0, 1, 2]))
## 表示(1,0)=4>3, (1,1)=5>3, (1,2)=6>3 這3組是 a>3


[[1 2 3]
 [4 5 6]]
(array([1, 1, 1]), array([0, 1, 2]))


## 算術計算

In [233]:
a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.multiply(a,b)
print(c)      # [2 4 6]

x = np.array([[2,3],[2,3]])
y = np.array([[2,2],[3,3]])
z = np.multiply(x,y)
print(z)      # [[4 6] [6 9]]

[2 4 6]
[[4 6]
 [6 9]]


### 數學函數

In [ ]:
# 三角函數
# 四捨五入
# sum()
# prod()
# sqrt()
# gcd()
# lcm()
# absolute()


### Numpy中的隨機數
比起 python built-in的 random多了對 array的方便功能

In [245]:
print(np.random.random((3,2)))

[[0.30888862 0.3527454 ]
 [0.15005932 0.79288808]
 [0.40758349 0.8089246 ]]


In [244]:
np.random.random(3)

array([0.23347016, 0.37974995, 0.344611  ])

In [248]:
print(np.random.randint(10,100,size=(3,2)))

[[33 78]
 [87 12]
 [80 53]]


In [254]:
a=np.random.random(10)
np.random.shuffle(a)
print(a)

[0.51023354 0.29423833 0.87488903 0.86753314 0.11993314 0.76745455
 0.15735414 0.43227285 0.80676015 0.01655178]
